name: Admin Template build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build
        run: mvn package

  release:
    name: Release Admin template to maven central
    runs-on: ubuntu-22.04
    needs: build
    env:
      user: ${{ secrets.user }}
      pass: ${{ secrets.pass }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: releases
          server-username: user
          server-password: pass
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Deploy snapshots
        if: "contains(github.ref, 'master') && !contains(github.event.head_commit.message, 'prepare release')"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/release-snapshots.sh"
          "${GITHUB_WORKSPACE}/release-snapshots.sh"
      - name: Release
        if: "contains(github.ref, 'master') && contains(github.event.head_commit.message, 'prepare release')"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/release.sh"
          "${GITHUB_WORKSPACE}/release.sh"
